
Chassis_type = "Rack Mount Chassis"
Chassis_Part_Number = "CHS1234"
Chassis_Serial_Number = "SN5678"
Chassis_Extra = "Chassis extra"
Board_Manufacturer = "qwfqwfg"
Board_Product_Name = "Board124"
Board_Serial_Number = "SN12345"
Board_Part_Number = "BP9876"
Board_Fruid = "FRU123"
Board_Extra = "Board extra"
Product_Manufacturer = "ProductMFC"
Product_Name = "Product1"
Product_Part_Number = "PN5678"
Product_Version = "V1.0.0"
Product_Serial_Number = "SN123456"
Product_Asset_Tag = "AssetTag"
Product_Extra = "Product extra"
