[chassis]
type = "Rack Mount"
part_number = "CHS1234"
serial_number = "SN5678"

[board]
manufacturer = "ExampleCorp"
product_name = "Board123"
serial_number = "SNB12345"
part_number = "BP9876"
fru_file_id = "FRU123"

[product]
manufacturer = "Manufact1"
product_name = "Product1"
part_number = "PN5678"
version = "V1.0.0"
serial_number = "SN123456"
asset_tag = "AssetTag"
